In [1]:
import pandas as pd 
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import re

In [2]:
data = pd.read_csv("/dsa/groups/casestudy2021f/group_2/data_part1.csv") #  data generated by Li's R code

In [3]:
data= data.iloc[:,2:]

In [4]:
data.shape

(786363, 34)

In [5]:
data.describe()

,accountNumber,customerId,creditLimit,availableMoney,year,month,day,transactionAmount,posEntryMode,posConditionCode,cardCVV,enteredCVV,cardLast4Digits,echoBuffer,currentBalance,merchantCity,merchantState,merchantZip,posOnPremises,recurringAuthInd
count,7.863630e+05,7.863630e+05,786363.000000,786363.000000,786363.0,786363.000000,786363.000000,786363.000000,782309.000000,785954.000000,786363.000000,786363.000000,786363.000000,0.0,786363.000000,0.0,0.0,0.0,0.0,0.0
mean,5.372326e+08,5.372326e+08,10759.464459,6250.725369,2016.0,6.648343,15.732804,136.985791,9.049943,3.271980,544.467338,544.183857,4757.417799,NaN,4508.739089,NaN,NaN,NaN,NaN,NaN
std,2.554211e+08,2.554211e+08,11636.174890,8880.783989,0.0,3.436256,8.780564,147.725569,16.774130,9.809023,261.524220,261.551254,2996.583810,NaN,6457.442068,NaN,NaN,NaN,NaN,NaN
min,1.000881e+08,1.000881e+08,250.000000,-1005.630000,2016.0,1.000000,1.000000,0.000000,2.000000,1.000000,100.000000,0.000000,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,NaN
25%,3.301333e+08,3.301333e+08,5000.000000,1077.420000,2016.0,4.000000,8.000000,33.650000,2.000000,1.000000,310.000000,310.000000,2178.000000,NaN,689.910000,NaN,NaN,NaN,NaN,NaN
50%,5.074561e+08,5.074561e+08,7500.000000,3184.860000,2016.0,7.000000,16.000000,87.900000,5.000000,1.000000,535.000000,535.000000,4733.000000,NaN,2451.760000,NaN,NaN,NaN,NaN,NaN
75%,7.676200e+08,7.676200e+08,15000.000000,7500.000000,2016.0,10.000000,23.000000,191.480000,9.000000,1.000000,785.000000,785.000000,7338.000000,NaN,5291.095000,NaN,NaN,NaN,NaN,NaN
max,9.993896e+08,9.993896e+08,50000.000000,50000.000000,2016.0,12.000000,31.000000,2011.540000,90.000000,99.000000,998.000000,998.000000,9998.000000,NaN,47498.810000,NaN,NaN,NaN,NaN,NaN

In [6]:
null_count = data.isnull().sum().sort_values(ascending = False)

percent = (data.isnull().sum()/(data.shape[0])*100)
missing_df = pd.concat([null_count, percent], axis=1, keys=['missing_values', 'percent'])
missing_df

                          missing_values     percent
recurringAuthInd                  786363  100.000000
posOnPremises                     786363  100.000000
merchantZip                       786363  100.000000
merchantState                     786363  100.000000
merchantCity                      786363  100.000000
echoBuffer                        786363  100.000000
acqCountry                          4562    0.580139
pos_Description                     4054    0.515538
posEntryMode                        4054    0.515538
merchantCountryCode                  724    0.092069
transactionType                      698    0.088763
posConditionCode                     409    0.052012
accountNumber                          0    0.000000
cardLast4Digits                        0    0.000000
currentBalance                         0    0.000000
cardCVV                                0    0.000000
cardPresent                            0    0.000000
expirationDateKeyInMatch               0    0.000000
enteredCVV                             0    0.000000
currentExpDate                         0    0.000000
dateOfLastAddressChange                0    0.000000
accountOpenDate                        0    0.000000
customerId                             0    0.000000
merchantCategoryCode                   0    0.000000
merchantName                           0    0.000000
Amount_classify                        0    0.000000
transactionAmount                      0    0.000000
day                                    0    0.000000
month                                  0    0.000000
year                                   0    0.000000
transactionDateTime                    0    0.000000
availableMoney                         0    0.000000
creditLimit                            0    0.000000
isFraud                                0    0.000000

In [7]:
data.select_dtypes(include = object).columns

Index(['transactionDateTime', 'Amount_classify', 'merchantName', 'acqCountry',
       'merchantCountryCode', 'pos_Description', 'merchantCategoryCode',
       'currentExpDate', 'accountOpenDate', 'dateOfLastAddressChange',
       'transactionType'],
      dtype='object')

In [8]:
#date columns not preserved while converting to R dataframe and on bringing it back to Python
df_date_col = ['transactionDateTime','currentExpDate','accountOpenDate','dateOfLastAddressChange']

for col in df_date_col:
    data.loc[:,col]= data.loc[:,col].astype('datetime64[ns]')

In [9]:
#Req 1d = Categorical columns – Ensure that unique values are not mispelled so as to ensure/validate uniqueness of values

categorical_col= data.select_dtypes(include = object).columns.to_list() # filter columns with categorical data type


# categorical_col_with_data = [] #categorical columns with data
# for i in categorical_col:
# #     print(missing_df[missing_df.index==i])
#     categorical_col_with_data.append(i)

#     if (missing_df[missing_df.index==i]['missing_values']!=0).bool():
        
for col in categorical_col:
    print(col,'\n',data.loc[:,col].unique())

Amount_classify
 ['$50-100' '<$50' '$500-1000' '$100-200' '$200-300' '$300-500' '>=$1000']
merchantName
 ['Uber' 'AMC #191138' 'Play Store' ... 'ATT #141119' 'EZ Wireless #200746'
 'Runners #747070']
acqCountry
 ['US' nan 'CAN' 'MEX' 'PR']
merchantCountryCode
 ['US' 'CAN' nan 'PR' 'MEX']
pos_Description
 ['Magnetic stripe read.'
 'PAN entry via electronic commerce, including chip.'
 'Integrated circuit card read; card data reliable.'
 'Chip card was unable to process/magnetic stripe read default.'
 'Magnetic stripe read and extract content of Track 1 or Track 2 included (CVV check is possible).'
 nan]
merchantCategoryCode
 ['rideshare' 'entertainment' 'mobileapps' 'fastfood' 'food_delivery'
 'auto' 'online_retail' 'gym' 'health' 'personal care' 'food' 'fuel'
 'online_subscriptions' 'online_gifts' 'hotels' 'airline' 'furniture'
 'subscriptions' 'cable/phone']
transactionType
 ['PURCHASE' 'ADDRESS_VERIFICATION' 'REVERSAL' nan]

In [10]:
#From the above code only Merchant name needs to be checked for duplicates.
# Merchant name as seen below has lot of duplicates due to number being tagged at the end. Code to clear this tag
data.loc[:,'merchantName'].unique().tolist()[0:20]

['Uber',
 'AMC #191138',
 'Play Store',
 'Tim Hortons #947751',
 'In-N-Out #422833',
 'Krispy Kreme #685312',
 'Shake Shack #968081',
 'Burger King #486122',
 'Five Guys #510989',
 "Auntie Anne's #747964",
 'GreenCook',
 'Washington Repair',
 'Eazy Tire',
 'Convenient Auto Services',
 'Shell Auto Body',
 'Fast Auto Services',
 'staples.com',
 'Convenient Repair',
 'Shell Repair',
 'Eazy Repair']

In [11]:
#code test for first 5 rows
pattern = r"(\w.*[^#0-9]+)"

for row in range(5):
    print('row-',row,'\n',data.loc[row,'merchantName'])
    print(str(re.findall(pattern,data.loc[row,'merchantName'])[0].strip()))
    print()
    
# for row in range(100000):
#     data.loc[row,'merchantName'] = re.findall(pattern,data.loc[row,'merchantName'])[0]

row- 0
 Uber
Uber

row- 1
 AMC #191138
AMC

row- 2
 Play Store
Play Store

row- 3
 Play Store
Play Store

row- 4
 Tim Hortons #947751
Tim Hortons

In [12]:
pattern = r"(\w.*[^#0-9]+)"

unique_merchant = list(set(data.loc[:,'merchantName']))

unique_dict = {}

for i in range(len(unique_merchant)):
    unique_dict[unique_merchant[i]] = re.findall(pattern,unique_merchant[i])[0].strip()
    
merchant_name_uq = []

for i in range(data.shape[0]):
    merchant_name_uq.append(unique_dict[data.loc[i,'merchantName']])

data['merchant_name_uq'] = merchant_name_uq

In [13]:
data.columns = [i.lower() for i in data.columns]

In [14]:
data = data.loc[:,data.columns.sort_values()]
data.head().T

,0,1,2,3,4
accountnumber,737265056,737265056,737265056,737265056,830329091
accountopendate,2015-03-14 00:00:00,2015-03-14 00:00:00,2015-03-14 00:00:00,2015-03-14 00:00:00,2015-08-06 00:00:00
acqcountry,US,US,US,US,US
amount_classify,$50-100,$50-100,<$50,<$50,$50-100
availablemoney,5000.0,5000.0,5000.0,5000.0,5000.0
cardcvv,414,486,486,486,885
cardlast4digits,1803,767,767,767,3143
cardpresent,False,True,False,False,True
creditlimit,5000,5000,5000,5000,5000
currentbalance,0.0,0.0,0.0,0.0,0.0
currentexpdate,2023-06-01 00:00:00,2024-02-01 00:00:00,2025-08-01 00:00:00,2025-08-01 00:00:00,2029-10-01 00:00:00
customerid,737265056,737265056,737265056,737265056,830329091
dateoflastaddresschange,2015-03-14 00:00:00,2015-03-14 00:00:00,2015-03-14 00:00:00,2015-03-14 00:00:00,2015-08-06 00:00:00
day,13,11,8,10,24
echobuffer,NaN,NaN,NaN,NaN,NaN
enteredcvv,414,486,486,486,885
expirationdatekeyinmatch,False,False,False,False,False
isfraud,False,False,False,False,False
merchant_name_uq,Uber,AMC,Play Store,Play Store,Tim Hortons
merchantcategorycode,rideshare,entertainment,mobileapps,mobileapps,fastfood
merchantcity,NaN,NaN,NaN,NaN,NaN
merchantcountrycode,US,US,US,US,US
merchantname,Uber,AMC #191138,Play Store,Play Store,Tim Hortons #947751
merchantstate,NaN,NaN,NaN,NaN,NaN
merchantzip,NaN,NaN,NaN,NaN,NaN
month,8,10,11,12,3
pos_description,Magnetic stripe read.,"PAN entry via electronic commerce, including c...","PAN entry via electronic commerce, including c...","PAN entry via electronic commerce, including c...",Magnetic stripe read.
posconditioncode,1.0,1.0,1.0,1.0,1.0
posentrymode,2.0,9.0,9.0,9.0,2.0
posonpremises,NaN,NaN,NaN,NaN,NaN
recurringauthind,NaN,NaN,NaN,NaN,NaN
transactionamount,98.55,74.51,7.47,7.47,71.18
transactiondatetime,2016-08-13 14:00:00,2016-10-11 05:00:00,2016-11-08 09:00:00,2016-12-10 02:00:00,2016-03-24 21:00:00
transactiontype,PURCHASE,PURCHASE,PURCHASE,PURCHASE,PURCHASE
year,2016,2016,2016,2016,2016

In [70]:
data['posentrymode'].unique()

array([ 2.,  9.,  5., 80., 90., nan])

In [68]:
def online_instore(x):
    if x == 2 or x == 5 or x ==90:
        return 'instore'
    
    elif x == 9 or x == 80:
        return 'electronic'
    else:
        return 'missing'

data['iselectronic'] = data['posentrymode'].apply(online_instore)

In [69]:
data['iselectronic'].value_counts()

instore       530545
electronic    251764
missing         4054
Name: iselectronic, dtype: int64

In [85]:
data.loc[:,('iselectronic','isfraud')].groupby(['iselectronic','isfraud']).size().unstack()

isfraud        False  True
iselectronic
electronic    245865   5899
instore       524296   6249
missing         3785    269

In [87]:
download_directory = '/dsa/groups/casestudy2021f/group_2'
clean_file_name = 'curated_data_m2.csv'
data.to_csv(download_directory+'/'+clean_file_name)